language: node_js
sudo: false
node_js:
  - "node"

os:
  - osx
  # Skip testing for Linux. For some reason it fails https://travis-ci.org/mlewand/vscode-selection-flip/jobs/606522364
  # even with ancient nodejs and Code version https://travis-ci.org/mlewand/vscode-selection-flip/jobs/606529052
  # - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install
script:
  - npm test --silent